# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('date_Added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='toy',
            field=models.ManyToManyField(related_name='users', to='login_register.Toy'),
        ),
    ]
